# Copy this file to .streamlit/secrets.toml for local development
# or paste its contents into the Secrets section in Streamlit Community Cloud.

[[auth.users]]
username = "Admin"
display_name = "PjoterDev"
role = "Admin"
active = true
salt = "2dca7cf9f423d3efd485450127c60d11"
password_hash = "8ff0d8d54e61cf684a163ea88eda74a7a1de38098359269a123d6a6c4704146e"
