[theme]
base = "light"
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7FAFC"
textColor = "#172033"
font = "sans serif"

[server]
headless = true
runOnSave = false
maxUploadSize = 300
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false

[logger]
level = "error"
